
import type { Asset } from "@/types";
import { EQUIPMENT_TYPE_MAP } from "@/types";

const today = new Date("2025-09-01");

function daysAgo(n: number) {
  const d = new Date(today);
  d.setDate(d.getDate() - n);
  return d.toISOString();
}

function daysFromNow(n: number) {
  const d = new Date(today);
  d.setDate(d.getDate() + n);
  return d.toISOString();
}

export const ASSETS: Asset[] = [
  // ── EQX1001 — Excavator, S003, OP101, active but high idle ───────────────
  {
    id: "EQX1001",
    equipmentTypeId: 1,
    equipmentTypeName: EQUIPMENT_TYPE_MAP[1],
    status: "IDLE",
    riskLevel: "MEDIUM",
    siteId: "S003",
    siteName: "Eastfield Construction Hub",
    operatorId: "OP101",
    operatorName: "Marcus Reyes",
    rentalStartDate: "2025-04-01",
    expectedReturnDate: "2025-04-16",
    actualReturnDate: null,
    engineHoursPerDay: 1.5,
    idleHoursPerDay: 10,
    operatingDays: 15,
    totalEngineHours: 22.5,
    totalIdleHours: 150,
    utilizationPct: 13,
    fuelLevelPct: 42,
    condition: "GOOD",
    lat: 40.1164,
    lng: -88.2434,
    lastTelemetryAt: daysAgo(0),
    notes: "High idle ratio — monitor",
  },
  // ── EQX1002 — Crane, no site, no operator, overdue ───────────────────────
  {
    id: "EQX1002",
    equipmentTypeId: 4,
    equipmentTypeName: EQUIPMENT_TYPE_MAP[4],
    status: "UNASSIGNED",
    riskLevel: "HIGH",
    siteId: null,
    siteName: null,
    operatorId: null,
    operatorName: null,
    rentalStartDate: "2025-03-10",
    expectedReturnDate: "2025-03-30",
    actualReturnDate: null,
    engineHoursPerDay: 0,
    idleHoursPerDay: 11,
    operatingDays: 20,
    totalEngineHours: 0,
    totalIdleHours: 220,
    utilizationPct: 0,
    fuelLevelPct: 78,
    condition: "GOOD",
    lat: null,
    lng: null,
    lastTelemetryAt: daysAgo(3),
    notes: "No site or operator — overdue return",
  },
  // ── EQX1003 — Bulldozer, S002, OP203, good utilization ───────────────────
  {
    id: "EQX1003",
    equipmentTypeId: 10,
    equipmentTypeName: EQUIPMENT_TYPE_MAP[10],
    status: "ACTIVE",
    riskLevel: "LOW",
    siteId: "S002",
    siteName: "Highland Cut Site",
    operatorId: "OP203",
    operatorName: "James Okafor",
    rentalStartDate: "2025-02-15",
    expectedReturnDate: "2025-03-11",
    actualReturnDate: null,
    engineHoursPerDay: 7.5,
    idleHoursPerDay: 0.5,
    operatingDays: 25,
    totalEngineHours: 187.5,
    totalIdleHours: 12.5,
    utilizationPct: 94,
    fuelLevelPct: 31,
    condition: "FAIR",
    lat: 40.6936,
    lng: -89.589,
    lastTelemetryAt: daysAgo(0),
    notes: "Low fuel — schedule refuel",
  },
  // ── EQX1004 — Excavator, S004, OP106, low utilization ────────────────────
  {
    id: "EQX1004",
    equipmentTypeId: 1,
    equipmentTypeName: EQUIPMENT_TYPE_MAP[1],
    status: "IDLE",
    riskLevel: "MEDIUM",
    siteId: "S004",
    siteName: "Northgate Infrastructure",
    operatorId: "OP106",
    operatorName: "Daniel Nguyen",
    rentalStartDate: "2025-05-05",
    expectedReturnDate: "2025-05-15",
    actualReturnDate: null,
    engineHoursPerDay: 2,
    idleHoursPerDay: 9,
    operatingDays: 10,
    totalEngineHours: 20,
    totalIdleHours: 90,
    utilizationPct: 18,
    fuelLevelPct: 65,
    condition: "GOOD",
    lat: 42.2711,
    lng: -89.0937,
    lastTelemetryAt: daysAgo(1),
    notes: null,
  },
  // ── EQX1005 — Bulldozer, S006, OP301, excellent utilization ──────────────
  {
    id: "EQX1005",
    equipmentTypeId: 10,
    equipmentTypeName: EQUIPMENT_TYPE_MAP[10],
    status: "ACTIVE",
    riskLevel: "LOW",
    siteId: "S006",
    siteName: "Southern Corridor Project",
    operatorId: "OP301",
    operatorName: "Elena Vasquez",
    rentalStartDate: "2025-01-01",
    expectedReturnDate: "2025-01-31",
    actualReturnDate: null,
    engineHoursPerDay: 8,
    idleHoursPerDay: 0,
    operatingDays: 30,
    totalEngineHours: 240,
    totalIdleHours: 0,
    utilizationPct: 100,
    fuelLevelPct: 55,
    condition: "FAIR",
    lat: 37.7273,
    lng: -89.2168,
    lastTelemetryAt: daysAgo(0),
    notes: "Excellent utilization",
  },
  // ── EQX1006 — Grader, S001, OP114, moderate idle ─────────────────────────
  {
    id: "EQX1006",
    equipmentTypeId: 2,
    equipmentTypeName: EQUIPMENT_TYPE_MAP[2],
    status: "ACTIVE",
    riskLevel: "MEDIUM",
    siteId: "S001",
    siteName: "Riverside Quarry",
    operatorId: "OP114",
    operatorName: "Sarah Kowalski",
    rentalStartDate: "2025-04-05",
    expectedReturnDate: "2025-04-23",
    actualReturnDate: null,
    engineHoursPerDay: 3,
    idleHoursPerDay: 6,
    operatingDays: 18,
    totalEngineHours: 54,
    totalIdleHours: 108,
    utilizationPct: 33,
    fuelLevelPct: 87,
    condition: "GOOD",
    lat: 39.7817,
    lng: -89.6501,
    lastTelemetryAt: daysAgo(0),
    notes: null,
  },
  // ── EQX1007 — THE HERO SCENARIO: Excavator, no site, no operator, 0 runtime
  {
    id: "EQX1007",
    equipmentTypeId: 1,
    equipmentTypeName: EQUIPMENT_TYPE_MAP[1],
    status: "UNASSIGNED",
    riskLevel: "CRITICAL",
    siteId: null,
    siteName: null,
    operatorId: null,
    operatorName: null,
    rentalStartDate: "2025-03-20",
    expectedReturnDate: "2025-04-01",
    actualReturnDate: null,
    engineHoursPerDay: 0,
    idleHoursPerDay: 12,
    operatingDays: 12,
    totalEngineHours: 0,
    totalIdleHours: 144,
    utilizationPct: 0,
    fuelLevelPct: 91,
    condition: "GOOD",
    lat: null,           // location unknown
    lng: null,
    lastTelemetryAt: daysAgo(0),
    notes: "CRITICAL: Unassigned. No runtime. 12h/day idle. Recommend reassign to S003.",
  },
  // ── EQX1008 — Dump Truck, S003, return due soon ───────────────────────────
  {
    id: "EQX1008",
    equipmentTypeId: 0,
    equipmentTypeName: EQUIPMENT_TYPE_MAP[0],
    status: "RETURN_DUE",
    riskLevel: "MEDIUM",
    siteId: "S003",
    siteName: "Eastfield Construction Hub",
    operatorId: "OP205",
    operatorName: "Tyler Brandt",
    rentalStartDate: "2025-08-15",
    expectedReturnDate: daysFromNow(1),
    actualReturnDate: null,
    engineHoursPerDay: 5.5,
    idleHoursPerDay: 2,
    operatingDays: 17,
    totalEngineHours: 93.5,
    totalIdleHours: 34,
    utilizationPct: 73,
    fuelLevelPct: 44,
    condition: "GOOD",
    lat: 40.1164,
    lng: -88.2434,
    lastTelemetryAt: daysAgo(0),
    notes: "Return due tomorrow",
  },
  // ── EQX1009 — Roller, S005, overdue ──────────────────────────────────────
  {
    id: "EQX1009",
    equipmentTypeId: 3,
    equipmentTypeName: EQUIPMENT_TYPE_MAP[3],
    status: "OVERDUE",
    riskLevel: "HIGH",
    siteId: "S005",
    siteName: "Lakefront Development",
    operatorId: "OP310",
    operatorName: "Amos Kariuki",
    rentalStartDate: "2025-08-01",
    expectedReturnDate: daysAgo(5),
    actualReturnDate: null,
    engineHoursPerDay: 6,
    idleHoursPerDay: 2,
    operatingDays: 26,
    totalEngineHours: 156,
    totalIdleHours: 52,
    utilizationPct: 75,
    fuelLevelPct: 28,
    condition: "FAIR",
    lat: 42.3636,
    lng: -87.8448,
    lastTelemetryAt: daysAgo(0),
    notes: "5 days overdue — contact site immediately",
  },
  // ── EQX1010 — Forklift Standard, S001, active ────────────────────────────
  {
    id: "EQX1010",
    equipmentTypeId: 6,
    equipmentTypeName: EQUIPMENT_TYPE_MAP[6],
    status: "ACTIVE",
    riskLevel: "LOW",
    siteId: "S001",
    siteName: "Riverside Quarry",
    operatorId: "OP402",
    operatorName: "Lisa Thornton",
    rentalStartDate: "2025-08-10",
    expectedReturnDate: daysFromNow(10),
    actualReturnDate: null,
    engineHoursPerDay: 7,
    idleHoursPerDay: 1,
    operatingDays: 22,
    totalEngineHours: 154,
    totalIdleHours: 22,
    utilizationPct: 88,
    fuelLevelPct: 70,
    condition: "EXCELLENT",
    lat: 39.7817,
    lng: -89.6501,
    lastTelemetryAt: daysAgo(0),
    notes: null,
  },
  // ── EQX1011 — Truck, S002, active ────────────────────────────────────────
  {
    id: "EQX1011",
    equipmentTypeId: 12,
    equipmentTypeName: EQUIPMENT_TYPE_MAP[12],
    status: "ACTIVE",
    riskLevel: "LOW",
    siteId: "S002",
    siteName: "Highland Cut Site",
    operatorId: "OP503",
    operatorName: "Kevin Shah",
    rentalStartDate: "2025-08-20",
    expectedReturnDate: daysFromNow(14),
    actualReturnDate: null,
    engineHoursPerDay: 6.5,
    idleHoursPerDay: 1.5,
    operatingDays: 12,
    totalEngineHours: 78,
    totalIdleHours: 18,
    utilizationPct: 81,
    fuelLevelPct: 62,
    condition: "GOOD",
    lat: 40.6936,
    lng: -89.589,
    lastTelemetryAt: daysAgo(0),
    notes: null,
  },
  // ── EQX1012 — Tanker, S005, overdue ──────────────────────────────────────
  {
    id: "EQX1012",
    equipmentTypeId: 9,
    equipmentTypeName: EQUIPMENT_TYPE_MAP[9],
    status: "OVERDUE",
    riskLevel: "HIGH",
    siteId: "S005",
    siteName: "Lakefront Development",
    operatorId: "OP611",
    operatorName: "Maria Gutierrez",
    rentalStartDate: "2025-07-25",
    expectedReturnDate: daysAgo(3),
    actualReturnDate: null,
    engineHoursPerDay: 4,
    idleHoursPerDay: 4,
    operatingDays: 38,
    totalEngineHours: 152,
    totalIdleHours: 152,
    utilizationPct: 50,
    fuelLevelPct: 15,
    condition: "FAIR",
    lat: 42.3636,
    lng: -87.8448,
    lastTelemetryAt: daysAgo(1),
    notes: "3 days overdue. Low fuel.",
  },
  // ── EQX1013 — Bucket Loader, S003, active high utilization ───────────────
  {
    id: "EQX1013",
    equipmentTypeId: 7,
    equipmentTypeName: EQUIPMENT_TYPE_MAP[7],
    status: "ACTIVE",
    riskLevel: "LOW",
    siteId: "S003",
    siteName: "Eastfield Construction Hub",
    operatorId: "OP205",
    operatorName: "Tyler Brandt",
    rentalStartDate: "2025-08-18",
    expectedReturnDate: daysFromNow(8),
    actualReturnDate: null,
    engineHoursPerDay: 9,
    idleHoursPerDay: 0,
    operatingDays: 14,
    totalEngineHours: 126,
    totalIdleHours: 0,
    utilizationPct: 100,
    fuelLevelPct: 48,
    condition: "GOOD",
    lat: 40.1164,
    lng: -88.2434,
    lastTelemetryAt: daysAgo(0),
    notes: null,
  },
  // ── EQX1034 — Excavator, S003, return due tomorrow (EXQ1034 scenario) ─────
  {
    id: "EQX1034",
    equipmentTypeId: 1,
    equipmentTypeName: EQUIPMENT_TYPE_MAP[1],
    status: "RETURN_DUE",
    riskLevel: "MEDIUM",
    siteId: "S003",
    siteName: "Eastfield Construction Hub",
    operatorId: "OP101",
    operatorName: "Marcus Reyes",
    rentalStartDate: "2025-08-20",
    expectedReturnDate: daysFromNow(1),
    actualReturnDate: null,
    engineHoursPerDay: 4.5,
    idleHoursPerDay: 3,
    operatingDays: 12,
    totalEngineHours: 54,
    totalIdleHours: 36,
    utilizationPct: 60,
    fuelLevelPct: 55,
    condition: "GOOD",
    lat: 40.1164,
    lng: -88.2434,
    lastTelemetryAt: daysAgo(0),
    notes: "Extension probability: 72%. Contact site.",
  },
];
