import type { Notification } from "@/types";

export const NOTIFICATIONS: Notification[] = [
  {
    id: "NOTIF-001",
    type: "ANOMALY",
    severity: "CRITICAL",
    title: "EQX1007 — Unassigned Asset Detected",
    description: "Excavator EQX1007 has no site or operator. 12h idle/day, 0 engine hours.",
    assetId: "EQX1007",
    linkHref: "/assets/EQX1007",
    isRead: false,
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "NOTIF-002",
    type: "OVERDUE",
    severity: "HIGH",
    title: "EQX1009 — 5 Days Overdue",
    description: "Roller at Lakefront Development is 5 days past return date.",
    assetId: "EQX1009",
    linkHref: "/assets/EQX1009",
    isRead: false,
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "NOTIF-003",
    type: "RETURN_DUE",
    severity: "WARNING",
    title: "EQX1034 — Return Due Tomorrow",
    description: "Excavator EQX1034 at S003 is due back tomorrow. Extension probability: 72%.",
    assetId: "EQX1034",
    linkHref: "/assets/EQX1034",
    isRead: false,
    createdAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
  },
  {
    id: "NOTIF-004",
    type: "FORECAST",
    severity: "HIGH",
    title: "S003 — Excavator Demand Increasing",
    description: "Forecast shows +2 excavator demand at Eastfield hub next week (87% confidence).",
    assetId: null,
    linkHref: "/forecasting",
    isRead: false,
    createdAt: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
  },
  {
    id: "NOTIF-005",
    type: "OVERDUE",
    severity: "HIGH",
    title: "EQX1012 — Tanker 3 Days Overdue",
    description: "Tanker at Lakefront Development is 3 days overdue. Critical fuel level: 15%.",
    assetId: "EQX1012",
    linkHref: "/assets/EQX1012",
    isRead: true,
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "NOTIF-006",
    type: "RECOMMENDATION",
    severity: "CRITICAL",
    title: "Action Required — Reassign EQX1007 to S003",
    description: "AI recommends reassigning EQX1007 to Eastfield hub. Confidence: 87%.",
    assetId: "EQX1007",
    linkHref: "/recommendations",
    isRead: false,
    createdAt: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
  },
];
